name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

name: Upload

jobs:
  build:
    name: Upload Release Asset
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Zip artifact
        run: zip EFI.zip ./* -r
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ./EFI.zip
          name: Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
