name: Zip repository and put on S3
on: [workflow_dispatch]

jobs:
  zip-n-push:
    name: Zip and Push
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          rm -rf <Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r/tree/main/1.0.0>.zip
          zip -r <Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r/tree/main/1.0.0>.zip <Lenovo-ThinkPad-X1-Tablet-Gen3-Kabylake-r/tree/main/1.0.0> -x ".git/*" ".github/*"
