name: Zip and Upload Artifact

on: 
  push:
    branches:
      - main  # You can specify the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Zip repository
      run: |
        rm -Rf TOOLS
        rm -Rf "Bios  V 1.49 SysReport"
        rm -Rf Screenshot
        rm -Rf "X1 Tablet 3°Gen.ioreg"
        rm -Rf README.md
        rm -Rf opencore-2024-01-10-205829.txt
        rm -Rf .gitignore       
        rm -Rf ".github"
        rm -Rf ".git"
        
        zip -r Lenovo_ThinkPad_X1-Tablet_Gen3.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Lenovo_ThinkPad_X1-Tablet_Gen3
        path: Lenovo_ThinkPad_X1-Tablet_Gen3.zip
        
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        bodyFile: "body.md"
