name: Zip and Upload Artifact

on: 
  push:
    branches:
      - main  # You can specify the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Zip repository
      run: |
      rm -R TOOLS
      rm -R Bios  V 1.49 SysReport
      rm -R Screenshot
      rm -R _config.yml
      rm -R X1 Tablet 3°Gen.ioreg
      rm -R opencore-2024-01-10-205829.txt
      
      zip -r repository.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: repository-zip
        path: repository.zip
